### ISSUE TITLE
make keys supplying not necessary

### ISSUE THREAD

**Issue by jazzl0ver** [markcaudill/haproxy-autoscale#27]
Hi,

Please make access and security keys non-required parameters, since they're not need when an instance's role has an appropriate policy setup

**Comment by markcaudill** [comment]
The changes should be fairly straightforward if you'd like to make them. Check out [lines 13 and 14](https://github.com/markcaudill/haproxy-autoscale/blob/master/update-haproxy.py#L13). If it works for you and nobody can come up with a good objection, I'd be more than happy to receive a pull request.

I don't actively maintain this project anymore due to time constraints and the inability to eat my own dog food anymore. I rely on active users like yourself for contributions.

**Comment by jazzl0ver** [comment]
No problem. Just sent you a pull request. Thank you!

**Comment by markcaudill** [comment]
Resolved in d75e76e. Thanks for your contribution!

**Comment by jazzl0ver** [comment]
Would you please accept all my other commits?

**Comment by markcaudill** [comment]
I merged the pull request. Did something get missed? It's entirely possible I screwed something up but I'm not sure what.

**Comment by jazzl0ver** [comment]
I apologies. Looks like all my commits have been merged. Thank you!

**Comment by markcaudill** [comment]
No problem! Thanks again for your commits.
